---
title: "inClass2_2019-April-08"
author: "Nicholas Bibeau"
date: "4/8/2019"
output: 
  html_document:
    toc: TRUE
    theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# Viewing Iris Dataset
```{r}
iris
```

# Normalizing Iris Dataset

## Creating Normalization Function
```{r}
normalize <- function(v, range=1){
    v.norm = (v - min(na.omit(v))) / (max(na.omit(v))-min(na.omit(v))) * range
    return(v.norm)
}

normalizeDataset <- function (data){
  data.norm <- data
  types <- sapply(data, is.numeric)
  for (i in 1:length(types)) {
    if(types[i]==TRUE){
      data.norm[ ,i] <- normalize(data[ ,i])
    }
  }
  return(data.norm)
}
```

## Applying Normalization to Dataset
```{r}

# Normalizing train dataset
iris.norm <- normalizeDataset(iris)
iris.norm

```


```{r}
eucli_distance <- function(x,y){
  d <- sqrt(sum((x-y)^2))
  return(d)
}


target <- dataset %>%
filter(customer_id==5) %>%
select(age,income)
target
dataset <- dataset %>%
rowwise() %>%
mutate(distance=
eucli_distance(c(age,income),target)
)
dataset

```

```{r}
neighbors <- dataset %>%
arrange(distance)
neighbors
```

# Determining distance
```{r}
neighbors %>%
select(customer_id,distance,product) %>%
  slice(1:5) %>%
  select(product)

```

# K=1: What is the product that Customer NO.5 will most likely purchase?
```{r}
# book
```

# K=2: What are top two products that Customer NO.5 will most likely purchase?
```{r}
# book, dvd
```

