---
title: "Week 7 Data Normalization (inclass)"
author: "Nicholas Bibeau"
date: "February 18, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
library(tidyverse)
```

# 11.3 Exercise

## Normalize all of the numeric attributes in the dataset train.csv and test.csv located at https://www.iun.edu/~cisjw/ds/files/data/. Store the normalized data with a new name train.norm and test.norm, respectively.


### Importing train.csv and test.csv
```{r}
train <- read_csv("https://www.iun.edu/~cisjw/ds/files/data/train.csv", na = "NA", col_types = cols(
  Survived = col_character(),
  Pclass = col_character(),
  Name = col_character(),
  Sex = col_character(),
  Age = col_integer(),
  SibSp = col_integer(),
  ParentChild = col_integer(),
  TicketNumber = col_character(),
  Fare = col_double(),
  Cabin = col_character(),
  Port = col_character(),
  LifeBoat = col_integer()
))

test <- read_csv("https://www.iun.edu/~cisjw/ds/files/data/test.csv", na = "NA", col_types = cols(
  Survived = col_character(),
  Pclass = col_character(),
  Name = col_character(),
  Sex = col_character(),
  Age = col_integer(),
  SibSp = col_integer(),
  ParentChild = col_integer(),
  TicketNumber = col_character(),
  Fare = col_double(),
  Cabin = col_character(),
  Port = col_character(),
  LifeBoat = col_integer()
))
```

## Create Normalization Functions
```{r}
#creating normalization function
normalize <- function(v, range=1){
    v.norm = (v - min(na.omit(v))) / (max(na.omit(v))-min(na.omit(v))) * range
    return(v.norm)
}

normalizeDataset <- function (data){
  data.norm <- data
  types <- sapply(data, is.numeric)
  for (i in 1:length(types)) {
    if(types[i]==TRUE){
      data.norm[ ,i] <- normalize(data[ ,i])
    }
  }
  return(data.norm)
}
```


## Data Normalization
```{r}
# Normalizing train dataset
train.norm <- normalizeDataset(train)
train.norm

# normalizing test dataset
test.norm <- normalizeDataset(test)
test.norm
```

